[package]
edition = "2021"
name = "mir"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
pest = "2.4.0"
pest_derive = "2.4.0"
