[workspace]
members = [
  "blots-core",
  "blots",
  "blots-wasm",
]
resolver = "2"

[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(wasm_bindgen_unstable_test_coverage)'] }
