[package]
edition = "2021"
name = "blots-core"
version = "0.1.0"

[dependencies]
anyhow = "1.0.86"
dyn-fmt = "0.4.3"
pest = "2.4.0"
pest_derive = "2.4.0"
serde = { version = "1.0.209", features = ["derive"] }
