[package]
edition = "2021"
name = "blots-core"
version = "0.1.0"

[dependencies]
anyhow = "1.0.86"
base64 = "0.21"
dyn-fmt = "0.4.3"
pest = "2.4.0"
pest_derive = "2.4.0"
regex = "1.10.2"
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0"
