name: Release CLI Binaries

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact: blots-linux-x86_64
            bin: blots
          - os: macos-latest
            artifact: blots-macos-x86_64
            bin: blots
          - os: macos-14
            artifact: blots-macos-arm64
            bin: blots

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Build
        run: cargo build --locked --release -p blots

      - name: Package binary
        run: tar czf ${{ matrix.artifact }}.tar.gz -C target/release ${{ matrix.bin }}

      - name: Upload release artifact
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.artifact }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
