name: Build and Release CLI

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build
        run: cargo build --locked --release --target ${{ matrix.target }} -p blots

      - name: Package
        run: |
          tar czf your-cli-${{ matrix.target }}.tar.gz \
            -C target/${{ matrix.target }}/release your-cli

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: your-cli-${{ matrix.target }}.tar.gz
